# linear regression(matrix)

# 1

In [3]:
import tensorflow as tf
import numpy as np

In [26]:
x_data=[ [1., 2., 0. ,3. ,5.] , [0., 2., 5., 2., 1.]]#2by5
y_data=[1.,2.,3.,4.,5.]#1by5

In [27]:
w=tf.Variable(tf.random.uniform((1,2), -1.0, 1.0))#1by2인 -1.0~1.0 난수
b=tf.Variable(tf.random.uniform((1,), -1.0, 1.0))#1byN
'''
1by2 * 2by5 = 1by5
 w   *   x  =   y
 
 1*W1 + 0*W2 + b = 1
 2*W1 + 2*W2 + b = 2
'''

'\n1by2 * 2by5 = 1by5\n w   *   x  =   y\n \n 1*W1 + 0*W2 + b = 1\n 2*W1 + 2*W2 + b = 2\n'

In [31]:
print(w,'\n',b)

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[-0.27168775, -0.81679153]], dtype=float32)> 
 <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.5745683], dtype=float32)>


In [29]:
learning_rate=tf.Variable(0.001)

In [35]:
for i in range(1001):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(w, x_data)+b
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))
        
        W_grad, b_grad = tape.gradient(cost, [w,b])
        w.assign_sub(learning_rate * W_grad)
        b.assign_sub(learning_rate * b_grad)
    
    if i%100==0:
        print("{:4} | {:10.3f} | {:10.3f} | {:10.3f} | {:10.3f}".format(
            i, cost.numpy(), w.numpy()[0][0], w.numpy()[0][1], b.numpy()[0]))

   0 |     26.782 |     -0.248 |     -0.794 |      0.584
 100 |      0.689 |      0.626 |      0.170 |      0.932
 200 |      0.351 |      0.687 |      0.315 |      0.943
 300 |      0.330 |      0.684 |      0.352 |      0.920
 400 |      0.321 |      0.683 |      0.368 |      0.894
 500 |      0.313 |      0.685 |      0.378 |      0.867
 600 |      0.305 |      0.689 |      0.385 |      0.842
 700 |      0.299 |      0.693 |      0.391 |      0.817
 800 |      0.292 |      0.698 |      0.396 |      0.792
 900 |      0.286 |      0.703 |      0.402 |      0.768
1000 |      0.280 |      0.707 |      0.406 |      0.745


# 2

In [36]:
X = tf.constant([[1., 2.], [3., 4.]])#2by2
y = tf.constant([[1.5], [3.5]])#2by1

In [53]:
W=tf.Variable(tf.random.normal( [2,1] )) #() == []
b=tf.Variable(tf.random.normal( (1,) ))
W

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-1.4232914],
       [ 1.6137878]], dtype=float32)>

In [54]:
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

In [70]:
n_epoch=1001
print("epoch | cost")

for i in range(n_epoch):
    with tf.GradientTape() as tape:
        y_pred = tf.matmul(X, W)+b
        cost = tf.reduce_mean(tf.square(y_pred -y))
    
    grads = tape.gradient(cost, [W,b])
    
    optimizer.apply_gradients(grads_and_vars = zip(grads, [W,b]))
    
    if i % 100 == 0:
        print("{:4} | {:10.3f}".format(i, cost.numpy()))#소수점이상 10자리
                                                        #소수점이하 3자리

epoch | cost
   0 |      0.000
 100 |      0.000
 200 |      0.000
 300 |      0.000
 400 |      0.000
 500 |      0.000
 600 |      0.000
 700 |      0.000
 800 |      0.000
 900 |      0.000
1000 |      0.000


In [71]:
print(W, b)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-0.43160564],
       [ 1.4315981 ]], dtype=float32)> <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-0.9315796], dtype=float32)>


In [72]:
tf.matmul(X,W)+b

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.500011 ],
       [3.4999957]], dtype=float32)>

In [75]:
y

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.5],
       [3.5]], dtype=float32)>

In [73]:
W.numpy()

array([[-0.43160564],
       [ 1.4315981 ]], dtype=float32)

In [74]:
b.numpy()

array([-0.9315796], dtype=float32)

# tf.multyply() = 원소곱
# tf.matmul() = 행렬곱